// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The kind:pipeline ENTITY body (a declared plan).
type PipelineInput struct {
	Version int64 `json:"version,omitempty"`

	Repo string `json:"repo,omitempty"`

	Gates []string `json:"gates,omitempty"`

	Redo struct {
		Max int64 `json:"max,omitempty"`

		Escalate_after int64 `json:"escalate_after,omitempty"`
	} `json:"redo,omitempty"`

	Concurrency struct {
		Lanes int64 `json:"lanes,omitempty"`
	} `json:"concurrency,omitempty"`

	Channels map[string]struct {
		Golden string `json:"golden"`

		Provision string `json:"provision"`
	} `json:"channels,omitempty"`

	Llm LLMSpec `json:"llm,omitempty"`

	Media MediaSpec `json:"media,omitempty"`

	Report ReportSpec `json:"report,omitempty"`

	// skills: the agent-stage skill corpus. corpus is a dir holding
	// <skill-name>/SKILL.md; it is REF-RESOLVED ($env.NAME / $workdir / ...)
	// and a relative result is joined with the run workdir, so a lane can point
	// at a generated corpus outside its own tree (e.g.
	// $env.EVAL_UMBRELLA/marketplace/distros/skills). Every stage skill: ref
	// names a skill in this corpus. An unresolvable ref FAILS the stage
	// informatively — the decorative-ref era is gone.
	Skills struct {
		Corpus string `json:"corpus"`
	} `json:"skills,omitempty"`

	Stages []Stage `json:"stages"`
}

// The LLM endpoint config (authored on the pipeline entity). Resolution:
// env overrides > the entity llm block > the built-in default (the local
// ollama server). An empty api_key means ABSENT: the client sends NO auth
// header (the local ollama needs none).
type LLMSpec struct {
	Base_url string `json:"base_url,omitempty"`

	Model string `json:"model,omitempty"`

	Api_key string `json:"api_key,omitempty"`
}

type MediaSpec struct {
	Files []string `json:"files"`

	Min map[string]int64 `json:"min"`

	Dir string `json:"dir"`
}

type ReportSpec struct {
	Template string `json:"template"`

	Frontmatter_schema string `json:"frontmatter_schema,omitempty"`

	Bed_template string `json:"bed_template,omitempty"`

	Control_bed_template string `json:"control_bed_template,omitempty"`
}

type Stage map[string]any

// #AgentStage: TYPED outputs (the untyped [...string] form is REMOVED — hard
// cutover). Each declared output is a field name -> #OutputType; the runner
// renders the contract into the prompt mechanically and validates the reply
// against it at decode. skill: refs are SKILL NAMES in the entity's
// skills.corpus.
//
// `cache` makes the agent's OUTPUT a COMMITTED ARTIFACT keyed by freshness: on a
// hit (the file exists and its key_field equals `key`) the declared outputs are
// READ from the file and the agent never runs; on a miss the agent runs normally.
// That is the render-once-per-<key> primitive a lane needs to reuse a committed
// plan (e.g. per pr@sha) instead of re-authoring it every run.
type AgentStage struct {
	Kind string `json:"kind"`

	Id string `json:"id"`

	Prompt string `json:"prompt"`

	Skill []string `json:"skill,omitempty"`

	Tools []string `json:"tools,omitempty"`

	Outputs map[string]OutputType `json:"outputs,omitempty"`

	Max_turns int64 `json:"max_turns,omitempty"`

	Redo RedoSpec `json:"redo,omitempty"`

	Skip_when string `json:"skip_when,omitempty"`

	Cache CacheSpec `json:"cache,omitempty"`
}

type OutputType struct {
	Type string `json:"type"`

	Enum []string `json:"enum,omitempty"`

	Description string `json:"description,omitempty"`
}

type RedoSpec struct {
	On_fail any/* CUE disjunction: (string|list) */ `json:"on_fail,omitempty"`

	Triggers map[string]string `json:"triggers,omitempty"`

	Max int64 `json:"max,omitempty"`

	Escalate_after int64 `json:"escalate_after,omitempty"`
}

type CacheSpec struct {
	Path string `json:"path"`

	Key string `json:"key"`

	Key_field string `json:"key_field,omitempty"`

	Source string `json:"source,omitempty"`
}

type ProbeStage struct {
	Kind string `json:"kind"`

	Id string `json:"id"`

	Verbs []string `json:"verbs"`

	Input map[string]any/* CUE top */ `json:"input,omitempty"`

	Outputs []string `json:"outputs,omitempty"`

	Redo RedoSpec `json:"redo,omitempty"`

	Skip_when string `json:"skip_when,omitempty"`
}

// #ProbeStage outputs: the probe's VALUE spreads as named outputs when it is a
// map (e.g. ledger_gate -> executed_checks/control_ok/media_ok/eval_steps/
// control_steps); a scalar value is exposed under the output named in `outputs`.
// #CheckStage is REMOVED: the custom bed-runner stage is gone. The org-wide
// evaluation is the ADE surface (#AdeStage): the bed's plan carries the oracle's
// agent-check: steps, graded by the live agent in the venue via the SDK.
type AdeStage struct {
	Kind string `json:"kind"`

	Id string `json:"id"`

	Bed string `json:"bed"`

	Fail_on []string `json:"fail_on,omitempty"`

	Redo RedoSpec `json:"redo,omitempty"`

	Skip_when string `json:"skip_when,omitempty"`
}

// #GenerateStage: render an inline template to `out`. `negate_checks` negates
// EVERY `checks` marker in the template. A per-marker transform
// (`${checks:negate}`, `${checks:json}`, `${var:yaml}`, `${var:indent}`,
// `${var:bullets}`) applies to that marker ALONE, so ONE template can render BOTH
// the treatment bed and its negative-control twin (plus a structured record with
// an indented multi-line report and bullet lists) into a single file. An unknown
// transform is a HARD error — never a silent no-op.
type GenerateStage struct {
	Kind string `json:"kind"`

	Id string `json:"id"`

	Template string `json:"template"`

	Vars map[string]any/* CUE top */ `json:"vars,omitempty"`

	Out string `json:"out"`

	Validate string `json:"validate,omitempty"`

	Negate_checks bool `json:"negate_checks,omitempty"`

	Skip_when string `json:"skip_when,omitempty"`
}

// #EmitStage: the SCHEMA-FIRST artifact writer — the replacement for hand-written
// YAML/JSON. Instead of rendering a free-form string template (which can emit
// invalid YAML, as a `what: text: with-colon` scalar did before this existed),
// `value` is assembled as a STRUCTURED value (the SAME ref grammar as `vars`),
// validated against the authored CUE `schema` def BEFORE any bytes hit disk, and
// only then marshalled to `out` (YAML by default). The record an agent or a lane
// produces therefore CANNOT be malformed: a value that violates the schema fails
// the stage informatively, exactly like an ingress kind body.
//
//	schema: one of THREE forms, each unified against `value` with Concreteness
//	        required (an unknown or wrong-typed field is a stage failure, never a
//	        silent drop):
//	          1. a bare def NAME (`#StageFindings`) resolving in the plugin's own
//	             served schema (schema/pipeline.cue);
//	          2. a `.cue` FILE path (`candy/eval-pr/record.cue`, project-relative
//	             to the run workdir) — the strongest form, a committed and
//	             reviewable schema the project owns; a `#Def` suffix
//	             (`record.cue#NotTestableRecord`) selects a def explicitly, a
//	             bare path uses the file's first `#Def`;
//	          3. a literal CUE source string (a self-contained def block).
//	value:  a structured map assembled from refs (@stage.output, $pr, $env.NAME).
//	        Every leaf resolves through the ref grammar; nested maps/lists are
//	        resolved recursively (resolveValue), so `@oracle.checks` lands as a
//	        real list of objects, not a stringified one.
//	format: "yaml" (default) | "json".
//
//	vars:   OPTIONAL named values for string-leaf TEMPLATES. A string leaf that
//	        contains `${name}` markers is rendered with the SHARED MARKER SYNTAX
//	        but emit's OWN transform set — NOT generate's full set:
//	          ${name}           scalar default (the value itself)
//	          ${name:indent}    the value as-is (a multi-line prose block)
//	          ${name:bullets}   a markdown bullet list (one line per element)
//	          ${name:yaml}      the value rendered inline as JSON
//	          ${name:json}      same as :yaml for a string leaf
//	        `negate` is DELIBERATELY REJECTED (a string leaf has no check to
//	        negate) and hard-errors like any other unknown transform. The RESULT
//	        is a string leaf of the structured value, so the CUE encoder owns the
//	        YAML quoting/block-scalar — which is what lets a prose field (the
//	        user-voice report) be composed WITHOUT a hand-written YAML template.
type EmitStage struct {
	Kind string `json:"kind"`

	Id string `json:"id"`

	Schema string `json:"schema"`

	Value map[string]any/* CUE top */ `json:"value"`

	Vars map[string]any/* CUE top */ `json:"vars,omitempty"`

	Out string `json:"out"`

	Format string `json:"format,omitempty"`

	Validate string `json:"validate,omitempty"`

	Skip_when string `json:"skip_when,omitempty"`
}

type MediaStage struct {
	Kind string `json:"kind"`

	Id string `json:"id"`

	Assemble bool `json:"assemble"`

	Transcode string `json:"transcode,omitempty"`

	Skip_when string `json:"skip_when,omitempty"`
}

type GateStage struct {
	Kind string `json:"kind"`

	Id string `json:"id"`

	Condition string `json:"condition"`

	Skip_when string `json:"skip_when,omitempty"`
}

type CommandStage struct {
	Kind string `json:"kind"`

	Id string `json:"id"`

	Command string `json:"command"`

	Expect_exit int64 `json:"expect_exit,omitempty"`
}

// #StageFinding — one row of the per-run ledger dump (stage-findings.yml). The
// dump is emitted schema-first (marshalled + validated), so it is always valid
// YAML — a debug artifact no reader can parse is worthless.
type StageFinding struct {
	Stage string `json:"stage"`

	Kind string `json:"kind"`

	Status string `json:"status"`

	Trigger string `json:"trigger,omitempty"`

	Message string `json:"message,omitempty"`

	Outputs map[string]any/* CUE top */ `json:"outputs,omitempty"`
}

type StageFindings []StageFinding

// Probe verb inputs (deterministic, engine-native).
type MediaGateInput struct {
	Dir string `json:"dir"`

	Files []any/* CUE closed list */ `json:"files"`

	Min map[string]int64 `json:"min"`
}

type LockAuditInput struct {
	Trees []any /* CUE closed list */ `json:"trees"`
}

type SequencingInput struct {
	Lanes int64 `json:"lanes"`

	Golden string `json:"golden"`
}

type HeadFreshnessInput struct {
	Plan_sha string `json:"plan_sha"`

	Pr int64 `json:"pr"`

	Repo string `json:"repo"`
}

type ConfigAuditInput struct {
	Bed string `json:"bed"`

	Pr int64 `json:"pr"`
}

type ResolveChannelInput struct {
	Channel string `json:"channel"`

	Channels map[string]struct {
		Golden string `json:"golden"`

		Provision string `json:"provision"`
	} `json:"channels"`
}

type EvidenceAuditInput struct {
	Dir string `json:"dir"`

	Files []any/* CUE closed list */ `json:"files"`

	Min map[string]int64 `json:"min"`

	Trees []any/* CUE closed list */ `json:"trees"`
}

// The P1 agent runtime input (the standalone + stage op).
type AgentRunInput struct {
	System_prompt string `json:"system_prompt"`

	Prompt string `json:"prompt"`

	Skill []string `json:"skill,omitempty"`

	Tools []string `json:"tools,omitempty"`
}
