// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The kind:pipeline ENTITY body (a declared plan).
type PipelineInput struct {
	Version int64 `json:"version,omitempty"`

	Gates []string `json:"gates,omitempty"`

	Redo struct {
		Max int64 `json:"max,omitempty"`

		Escalate_after int64 `json:"escalate_after,omitempty"`
	} `json:"redo,omitempty"`

	Concurrency struct {
		Lanes int64 `json:"lanes,omitempty"`
	} `json:"concurrency,omitempty"`

	Channels map[string]struct {
		Golden string `json:"golden"`

		Provision string `json:"provision"`
	} `json:"channels,omitempty"`

	Media MediaSpec `json:"media,omitempty"`

	Report ReportSpec `json:"report,omitempty"`

	Stages []Stage `json:"stages"`
}

type MediaSpec struct {
	Files []string `json:"files"`

	Min map[string]int64 `json:"min"`

	Dir string `json:"dir"`
}

type ReportSpec struct {
	Template string `json:"template"`

	Frontmatter_schema string `json:"frontmatter_schema,omitempty"`

	Bed_template string `json:"bed_template,omitempty"`
}

type Stage map[string]any

type AgentStage struct {
	Kind string `json:"kind"`

	Id string `json:"id"`

	Prompt string `json:"prompt"`

	Skill []string `json:"skill,omitempty"`

	Tools []string `json:"tools,omitempty"`

	Outputs []string `json:"outputs,omitempty"`

	Max_turns int64 `json:"max_turns,omitempty"`

	Redo RedoSpec `json:"redo,omitempty"`
}

type RedoSpec struct {
	On_fail any/* CUE disjunction: (string|list) */ `json:"on_fail,omitempty"`

	Triggers map[string]string `json:"triggers,omitempty"`
}

type ProbeStage struct {
	Kind string `json:"kind"`

	Id string `json:"id"`

	Verbs []string `json:"verbs"`

	Input map[string]any/* CUE top */ `json:"input,omitempty"`

	Outputs []string `json:"outputs,omitempty"`

	Redo RedoSpec `json:"redo,omitempty"`
}

// #CheckStage is REMOVED: the custom bed-runner stage is gone. The org-wide
// evaluation is the ADE surface (#AdeStage): the bed's plan carries the oracle's
// agent-check: steps, graded by the live agent in the venue via the SDK.
type AdeStage struct {
	Kind string `json:"kind"`

	Id string `json:"id"`

	Bed string `json:"bed"`

	Redo RedoSpec `json:"redo,omitempty"`
}

type GenerateStage struct {
	Kind string `json:"kind"`

	Id string `json:"id"`

	Template string `json:"template"`

	Vars map[string]any/* CUE top */ `json:"vars,omitempty"`

	Out string `json:"out"`

	Validate string `json:"validate,omitempty"`
}

type MediaStage struct {
	Kind string `json:"kind"`

	Id string `json:"id"`

	Assemble bool `json:"assemble"`

	Transcode string `json:"transcode,omitempty"`
}

type GateStage struct {
	Kind string `json:"kind"`

	Id string `json:"id"`

	Condition string `json:"condition"`
}

type CommandStage struct {
	Kind string `json:"kind"`

	Id string `json:"id"`

	Command string `json:"command"`

	Expect_exit int64 `json:"expect_exit,omitempty"`
}

// Probe verb inputs (deterministic, engine-native).
type MediaGateInput struct {
	Dir string `json:"dir"`

	Files []any/* CUE closed list */ `json:"files"`

	Min map[string]int64 `json:"min"`
}

type LockAuditInput struct {
	Trees []any /* CUE closed list */ `json:"trees"`
}

type SequencingInput struct {
	Lanes int64 `json:"lanes"`

	Golden string `json:"golden"`
}

type HeadFreshnessInput struct {
	Plan_sha string `json:"plan_sha"`

	Pr int64 `json:"pr"`

	Repo string `json:"repo"`
}

type ConfigAuditInput struct {
	Bed string `json:"bed"`

	Pr int64 `json:"pr"`
}

type ResolveChannelInput struct {
	Pr int64 `json:"pr"`

	Channels map[string]struct {
		Golden string `json:"golden"`

		Provision string `json:"provision"`
	} `json:"channels"`

	Default string `json:"default"`
}

type EvidenceAuditInput struct {
	Dir string `json:"dir"`

	Files []any/* CUE closed list */ `json:"files"`

	Min map[string]int64 `json:"min"`

	Trees []any/* CUE closed list */ `json:"trees"`
}

// The P1 agent runtime input (the standalone + stage op).
type AgentRunInput struct {
	System_prompt string `json:"system_prompt"`

	Prompt string `json:"prompt"`

	Skill []string `json:"skill,omitempty"`

	Tools []string `json:"tools,omitempty"`
}
